version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=chatgpt_db
      - DB_USER=user
      - DB_PASSWORD=password
    container_name: servicegpt-backend
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
    depends_on:
      - db
    command: >
      sh -c "sleep 30 &&
            alembic upgrade head &&
            uvicorn app.main:app --host 0.0.0.0 --port 8000"
    networks:
      - servicegpt-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: servicegpt-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - servicegpt-network

  db:
    image: mysql:8.0
    container_name: servicegpt-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chatgpt_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - servicegpt-network
    volumes:
      - mysql-data:/var/lib/mysql

networks:
  servicegpt-network:

volumes:
  mysql-data:
