"""Update user model

Revision ID: 85296525409c
Revises: 2e4b8ad425af
Create Date: 2025-02-17 09:26:56.584707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '85296525409c'
down_revision: Union[str, None] = '2e4b8ad425af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fullname', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('role', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.alter_column('users', 'hashed_password',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=75),
               type_=sa.String(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(collation='utf8mb4_general_ci', length=75),
               existing_nullable=False)
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'role')
    op.drop_column('users', 'fullname')
    # ### end Alembic commands ###
